@StoreAPI_HostAddress = http://localhost:5143/api
@StoreAPI_AccessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiaWFtc2FtaXQiLCJqdGkiOiI4NWY0YWIyOS1lYWNhLTQ3MTItYmRiNS02YTU2OGZhY2Y4MWIiLCJleHAiOjE3MTM0NTk5NzcsImlzcyI6IioiLCJhdWQiOiIqIn0.h7OQ6Dqrzk3Bo0kSaivuDUqNaNubDgrUE81ybbfi8v8

// Test connection to the StoreAPI
GET {{StoreAPI_HostAddress}}/Product/testconnect
Accept: application/json

###

// Get all products
GET {{StoreAPI_HostAddress}}/Product
Accept: application/json
Authorization: Bearer {{StoreAPI_AccessToken}}

###

// Get a product by ID
GET {{StoreAPI_HostAddress}}/Product/2
Accept: application/json
Authorization: Bearer {{StoreAPI_AccessToken}}

###

// Create a new product with file upload
POST {{StoreAPI_HostAddress}}/Product 
Authorization: Bearer {{StoreAPI_AccessToken}}
Accept: text/plain
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW 

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="product_id" 
5

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="category_id" 
1 

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="product_name" 
"Mobile Product New 2024"

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="unit_price" 
10

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="unit_in_stock" 
100

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="created_date" 
"2021-07-01T00:00:00"

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="modified_date" 
"2021-07-01T00:00:00"

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="category.category_id" 

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="category.category_name"

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="category.category_status"

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; 

filename="iphone.png" 
Content-Type: image/png 

< ./sample_images/iphone.png 
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

// Update a product
PUT {{StoreAPI_HostAddress}}/Product/5
Content-Type: application/json
Accept: application/json

{
  "category_id": 1,
  "product_name": "Mobile Product Updated",
  "unit_price": 20,
  "product_picture": "https://www.popticles.com/wp-content/uploads/2021/04/iphone-410311_1280-1024x682.jpg",
  "unit_in_stock": 100,
  "created_date": "2021-07-01T00:00:00",
  "modified_date": "2021-07-01T00:00:00"
}

###

// Delete a product
DELETE {{StoreAPI_HostAddress}}/Product/5
Accept: application/json